# Uncommentfeapp the next line to define a global platform for your project
platform :ios, '7.0'

target ‘RNBrowser’ do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for iyunbao

  #target 'hengqinlifeappTests' do
   # inherit! :search_paths
    # Pods for testing
  #end

  #target 'hengqinlifeappTests' do
  #  inherit! :search_paths
    # Pods for testing
  #end

pod 'AFNetworking', '~> 3.0’
pod 'Masonry', '~> 0.6.3'
pod 'SDWebImage', '~> 4.2.3'
end
